# Generated by Django 5.0.7 on 2024-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_alter_slider_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان بنر ')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='آدرس بنر')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='تصویر بنر')),
                ('postion', models.CharField(choices=[('product_list', 'بنر تبلیفاتی  لیست محصولات'), ('product_detail', 'بنر تبلیفاتی  جزییات محصولات')], max_length=250, verbose_name='محل قرارکیری')),
                ('is_active', models.BooleanField(verbose_name='فعال /غیر فعال')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر تبلیفاتی محصولات',
            },
        ),
    ]
