# Generated by Django 5.0.7 on 2024-09-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_merge_0006_banner_0007_auto_20220417_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
